development:
  adapter: postgresql
  encoding: unicode
  database: weddingseat_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: weddingseat_test
  pool: 5


production:
  encoding: unicode
  pool: 5
